---

- name: Create folder
  file: path={{ selenium.driver.chrome_dir }} state=directory mode=0755

- name: Unzip chrome driver
  unarchive: src={{ selenium.driver.url_repository }} dest={{ selenium.driver.chrome_dir }} copy=no mode=0755

- name: Add key repository
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: Add repository for browser Chrome
  apt_repository: repo='deb http://dl.google.com/linux/chrome/deb/ stable main' state=present

- name: Install the browser
  apt: pkg=google-chrome-stable state=present
