---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: chrome-debian.yml
  when: ansible_os_family == 'Debian'

- include: selenium.yml
  when: ansible_os_family == 'Debian'
