---

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: debian.yml
  when: ansible_os_family == 'Debian'

- name: Download chrome driver
  get_url: 
