---

- name: Install required
  apt: pkg={{ item }} state=present
  with_items:
    - unzip
    - tar

- include: chrome-debian.yml
  when: ansible_os_family == 'Debian'

- include: selenium.yml
  when: ansible_os_family == 'Debian'
